{% set version = '2.3-3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bio3d
  version: {{ version|replace("-", "_") }}

source:
  fn: bio3d_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/bio3d_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/bio3d/bio3d_{{ version }}.tar.gz


  sha256: f4b45847eb8a4175dacea659f30a8075769ec1ae19daec6842b0d72227b48633
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: XML, RCurl, lattice, ncdf4, igraph, bigmemory, knitr, testthat (>= 0.9.1), httr
requirements:
  build:
    - r-base
    - r-rcpp
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-rcpp
    - {{native}}gcc-libs   # [win]
    - libgcc               # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('bio3d')"  # [not win]
    - "\"%R%\" -e \"library('bio3d')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://thegrantlab.org/bio3d/, http://bitbucket.org/Grantlab/bio3d
  license: GPL (>= 2)
  summary: Utilities to process, organize and explore protein structure, sequence and dynamics
    data. Features include the ability to read and write structure, sequence and dynamic
    trajectory data, perform sequence and structure database searches, data summaries,
    atom selection, alignment, superposition, rigid core identification, clustering,
    torsion analysis, distance matrix analysis, structure and sequence conservation
    analysis, normal mode analysis, principal component analysis of heterogeneous structure
    data, and correlation network analysis from normal mode and molecular dynamics data.
    In addition, various utility functions are provided to enable the statistical and
    graphical power of the R environment to work with biological sequence and structural
    data. Please refer to the URLs below for more information.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: bio3d
# Title: Biological Structure Analysis
# Version: 2.3-3
# Authors@R: c(person("Barry", "Grant", role=c("aut", "cre"), email="bjgrant@umich.edu"), person("Xin-Qiu", "Yao", role="aut"), person("Lars", "Skjaerven", role="aut"),  person("Julien", "Ide", role="aut"))
# Author: Barry Grant [aut, cre],  Xin-Qiu Yao [aut],  Lars Skjaerven [aut],  Julien Ide [aut]
# VignetteBuilder: knitr
# LinkingTo: Rcpp
# Imports: Rcpp, parallel, grid, graphics, grDevices, stats, utils
# Suggests: XML, RCurl, lattice, ncdf4, igraph, bigmemory, knitr, testthat (>= 0.9.1), httr
# Depends: R (>= 3.1.0)
# LazyData: yes
# Description: Utilities to process, organize and explore protein structure, sequence and dynamics data. Features include the ability to read and write structure, sequence and dynamic trajectory data, perform sequence and structure database searches, data summaries, atom selection, alignment, superposition, rigid core identification, clustering, torsion analysis, distance matrix analysis, structure and sequence conservation analysis, normal mode analysis, principal component analysis of heterogeneous structure data, and correlation network analysis from normal mode and molecular dynamics data. In addition, various utility functions are provided to enable the statistical and graphical power of the R environment to work with biological sequence and structural data. Please refer to the URLs below for more information.
# Maintainer: Barry Grant <bjgrant@umich.edu>
# License: GPL (>= 2)
# URL: http://thegrantlab.org/bio3d/, http://bitbucket.org/Grantlab/bio3d
# RoxygenNote: 5.0.1
# NeedsCompilation: yes
# Packaged: 2017-07-29 19:26:07 UTC; xinqyao
# Repository: CRAN
# Date/Publication: 2017-07-31 04:23:33 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
